### ISSUE TITLE
All binaries in release tarball are Mach-O 64-bit x86_64 executable

### ISSUE THREAD

**Issue by simontesar** [eripa/prometheus-zfs#1]
Although their postfix suggests Linux, FreeBSD and Solaris binaries. 
```
~/Downloads/prometheus-zfs/bin: file *
prometheus-zfs-darwin:  Mach-O 64-bit executable x86_64
prometheus-zfs-freebsd: Mach-O 64-bit executable x86_64
prometheus-zfs-linux:   Mach-O 64-bit executable x86_64
prometheus-zfs-solaris: Mach-O 64-bit executable x86_64
```

**Comment by eripa** [comment]
Thanks for the report. It's fixed in v0.1.1
https://github.com/eripa/prometheus-zfs/releases/tag/v0.1.1

But please note the WIP state of this project. v0.1.0 and v0.1.1 is not recommended to use in production.
